/*
 * Stoatworks Labs — About window data for File Drop Batch.
 *
 * GENERATED by stoatworks-backend/scripts/sync-about.py on 2026-09-11. Do not
 * edit: the next sync overwrites it. The facts come from the website's
 * projects.json, which is the one place they are written down.
 *
 * `version` here is a fallback read from this repo's own manifest at sync
 * time. Anything with a build step injects the real one at build time and
 * overrides this.
 */
window.STOATWORKS_ABOUT = Object.assign({
  "name": "File Drop Batch",
  "slug": "nc-filedropbatch",
  "version": "v1.5.1",
  "hook": "Bulk file drops in Nextcloud",
  "licence": "AGPL-3.0",
  "guide": "https://stoatworks-labs.com/software/nc-filedropbatch/guide/",
  "page": "https://stoatworks-labs.com/software/nc-filedropbatch/",
  "repo": "https://github.com/stoatworks-labs/nc-filedropbatch"
}, window.STOATWORKS_ABOUT || {});
